compile:
	mcs -r:RestSharp.105.2.3/lib/net46/RestSharp.dll \
        -r:JWT.1.3.4/lib/3.5/JWT.dll  \
        -r:jose-jwt.2.2.0/lib/net461/jose-jwt.dll \
        -r:Newtonsoft.Json.10.0.1/lib/net45/Newtonsoft.Json.dll \
        Program.cs 

run:
	mono -r:RestSharp.105.2.3/lib/net46/RestSharp.dll \
        -r:JWT.1.3.4/lib/3.5/JWT.dll  \
        -r:jose-jwt.2.2.0/lib/net461/jose-jwt.dll \
        -r:Newtonsoft.Json.10.0.1/lib/net45/Newtonsoft.Json.dll \
        Program.exe
